apiVersion: v1
kind: ConfigMap
metadata: 
 name: mongodb-configmap
data:
 database_url: mongodb-service #this is the service name, since we have configured the ports and protocol there and it maps to our mongodb pod
